[monitor]
43.205.194.103 # Change according to yout Public ip which you receive in terraform output

[target]
43.205.236.27  # Change according to yout Public ip which you receive in terraform output
13.126.122.126 # Change according to yout Public ip which you receive in terraform output